import { IAppRoutes } from "../interfaces";

export const AppRoutes: IAppRoutes = {
  MAIN: "/",
  HOME: "/dashboard",
  LOGIN: "/login",
  MY_PROFILE: "/profile",
  EMPLOYEE: "/employee",
  ADD_EMPLOYEE: "/employee/add",
  VIEW_EMPLOYEE: "/employee/view/:id/:userName",
  EDIT_EMPLOYEE: "/employee/edit/:id/:userName",
  DEPARTMENT: "/department",
  ADD_DEPARTMENT: "/department/add",
  REGION: "/region",
  CARE_GIVER: "/caregiver",
  ADD_CARE_GIVER: "/caregiver/add",
  CARE_INSTITUTION: "/care-institution",
  CARE_INSTITUION_VIEW: "/care-institution/view/:id",
  CAREGIVER_TODO: "/caregiver-todo",
  CARE_INSTITUTION_TODO: "/care-institution-todo",
  CARE_GIVER_VIEW: "/caregiver/view/:id",
  ADD_CARE_INSTITUTION: "/care-institution/add/:id",
  CARE_INSTITUTION_TODO_HIDE_DONE: "/care-institution-todo/hide-done",
  CARE_INSTITUTION_TODO_HIDE_FUTURE: "/care-institution-todo/hide-future",
  CARE_INSTITUTION_TODO_REQUIREMENT: "/care-institution-todo/requirement",
  CARE_GIVER_HIDE_DONE: "/caregiver-todo/hide-done",
  CARE_GIVER_HIDE_FUTURE: "/caregiver-todo/hide-future",
  DOCUMENT_TEMPLATE_WORKING: "/working-proof",
  BULK_EMAIL_CAREGIVER: "/bulk-email-caregiver",
  EMAIL_SENT: "/sent-email",
  EMAIL_OUTBOX: "/outbox-email",
  EMAIL_QUEUE: "/email-queue",
  ALL_EMAILS: "/email",
  APPOINTMENT: "/appointment",
  PAGENOTFOUND: "/404",
  EMPLOYEE_ARCHIVE: "/employee/trash",
  CAREGIVER_ARCHIVE: "/caregiver/trash",
  CAREINSTITUTION_ARCHIVE: "/care-institution/trash",
  EMPLOYEE_LOGIN_HISTORY: "/employee/login-history",
  EMAIL_INBOX: "/inbox-email",
  //
  FURTHER: "/further",
  GLOBAL_CALENDAR: "/further/global-calendar",
  ATTRIBUTE_MANAGEMENT: "/further/attribute",
  EMAIL_TEMPLATE_MANAGEMENT: "/further/email-templates",
  BULK_EMAIL_CAREINSTITUTION: "/bulk-email-careinstitution",
  ALLINVOICES: "/invoices",
  INVOICESOLONA: "/invoice-solona",
  DROWINVOICE: "/drow-invoice",
  CREATEINVOICES: "/create-invoice",
  PRINTINVOICES: "/print-invoice",
  PAYSLIPFORM:"/pay-slip-form",
  HEALTHINSURANCEFORM:"/health-insurance-form"
};
